RADFISH-193 Simple Table Updates
NMFS-RADFish/boilerplate pull request #107
Opened 2024-05-28 18:04 UTC by melsoriano

* Refactored `TableWrapper` context provider to only manage state.
* Abstracted out the column creation to be on the same level where `TableWrapper` is imported (`index.jsx`).
* Moved `TableWrapper` to `packages` directory so that it can be eventually moved to the npm react-radfish package.
* Created docs on how to setup the table.

2024-05-28 19:38 UTC, brockinit commented on examples/simple-table/README.md
> +1. Install `react-table` if you haven't already: `npm install @tanstack/react-table`
Can we just update this to `npm install`? I think it might confuse folks into thinking that they have other things they should be worried about installing. Since the example has a `package.json` with all the necessary modules defined in it, I think it would be simpler to just instruct them to run the generic install command.

2024-05-28 19:42 UTC, brockinit commented on examples/simple-table/src/packages/contexts/TableWrapper.jsx
> +    pageSize: pageSize || 10,
Leave comment explaining that 10 is a default value. Also, please add 10 to a constant.

2024-05-28 19:42 UTC, brockinit commented on examples/simple-table/src/index.jsx
> +      <TableWrapper columnMap={columnMap} pageSize={10}>
Please set 10 as a constant

2024-05-28 19:43 UTC, brockinit requested changes
Left a few small requests!

2024-05-29 19:38 UTC, melsoriano commented on examples/simple-table/src/index.jsx
> +      <TableWrapper columnMap={columnMap} pageSize={10}>
Made changes here: https://github.com/NMFS-RADFish/boilerplate/pull/107/commits/ed2a41cfa129c00313ace76def4ef7ebdd1be8fa

2024-05-29 19:38 UTC, melsoriano commented on examples/simple-table/src/packages/contexts/TableWrapper.jsx
> +    pageSize: pageSize || 10,
Made changes here: https://github.com/NMFS-RADFish/boilerplate/pull/107/commits/ed2a41cfa129c00313ace76def4ef7ebdd1be8fa

2024-05-29 19:39 UTC, melsoriano commented on examples/simple-table/README.md
> +1. Install `react-table` if you haven't already: `npm install @tanstack/react-table`
Done ✅

2024-05-29 20:08 UTC, brockinit approved these changes

2024-05-29 20:08 UTC, merged