178 example package updates
NMFS-RADFish/boilerplate pull request #197
Opened 2024-09-27 20:36 UTC by jaygiang

issue #178 

Updated `@lhci/cli` from version `0.13.0` to `0.14.0`
  - There is a vulnerabilities in `ws` package version that is used within `@lhci/cli`. Updating it to `0.14.0` fixes the vulnerabilities warning.
    <img width="925" alt="Screenshot 2024-09-27 at 1 35 20 PM" src="https://github.com/user-attachments/assets/59621313-bcea-4440-873b-2ae0b4b7f532">
  - There are breaking changes in [0.14.0](https://github.com/GoogleChrome/lighthouse-ci/releases)
  - Tested `0.14.0` by running `lhci:mobile` and `lhci:desktop` with no errors. Also ran app and there are no problems. 

Created `compare-package.js` script to check for mismatches
  - checks dependencies between boilerplate root `package.json` and each example project
  - my thought process was have the core dependencies that exists in each example be in the root `package.json`. I'm sure this can use some fine tuning, so please leave any feedback
  - to run script, go to root and run `npm run check-dependency`
    - output example:
    <img width="858" alt="Screenshot 2024-09-27 at 11 34 11 AM" src="https://github.com/user-attachments/assets/7e7013f9-4a1a-4539-85a6-00453e348785">

2024-10-03 20:17 UTC, jaygiang commented
## Update:
- Created `dependabot.yml` to let it handle checking dependencies in `examples` and `packages`
  - I reverted the  `@lhci/cli" back to  `0.13.0` in the `computed-form-fields` example, but kept all the other examples to `0.14.0`. I did this so we can see if dependabot creates a PR if there needs to be an update due to vulnerabilities
- Removed compare packages script and dependencies in root `package.json`

2024-10-04 21:51 UTC, thgaskell requested changes
Please update to include template directory.

2024-10-04 22:51 UTC, jaygiang commented
@thgaskell added template and used directories

2024-10-04 23:15 UTC, thgaskell approved these changes

2024-10-04 23:15 UTC, merged