[RADFISH-51] Table component
NMFS-RADFish/boilerplate pull request #26
Opened 2024-02-02 18:09 UTC by gambinish

🚧 In progress

1. Table should render data from mock service worker, and be sorted on the client.

Todo:

1. Extend trussworks Table rather than importing directly into app
2. Allow for search queries to get passed to MSW, should return different data (column helper needs to be dynamic)
3. Unit tests

2024-02-06 17:39 UTC, brockinit commented on src/App.js
> +          <Routes>
I know it's not within the context of this PR, but I think it would be good for us to add documentation in all demo files. Can we annotate the `app.js` file so people know how to use it and what it's showing?

2024-02-06 17:40 UTC, brockinit commented on src/components/DemoTable.js
> +import { useEffect } from "react";
Similar to the other comment, can we please annotate this file with detailed comments on what's going on and how to leverage it?

2024-02-06 17:44 UTC, brockinit commented on src/contexts/TableWrapper.js
> +import React, { createContext } from "react";
Is this context meant to be used with the Demo form? Or used with all forms?

Can you please document this as well?

2024-02-06 17:45 UTC, brockinit commented on src/mocks/handlers.js
> +  http.get(MSW_ENDPOINT.TABLE, ({ request }) => {
Might be nice to leave a comment on each endpoint with a sample payload in JSON. I know it's technically shown below, but it doesn't hurt to be abundantly clear.

2024-02-06 17:46 UTC, brockinit requested changes
Implementation looks good. I mainly added comments around documenting things.

2024-02-06 18:09 UTC, gambinish commented
Yeah good call. I'll go ahead and add documentation here and try to sneak in unit tests as well.

2024-02-06 18:43 UTC, gambinish commented on src/contexts/TableWrapper.js
> +import React, { createContext } from "react";
Added comments here to `TableWrapper` and also added a few to `FormWrapper`

https://github.com/NMFS-RADFish/boilerplate/pull/26/commits/a28967cf861d4fe1cce40e31ca9fe515371f9860

2024-02-06 18:50 UTC, gambinish commented on src/mocks/handlers.js
> +  http.get(MSW_ENDPOINT.TABLE, ({ request }) => {
Documented MSW handlers here: https://github.com/NMFS-RADFish/boilerplate/pull/26/commits/1c2c8e6a61cab3fa10352ac199abac8b3e48507c

2024-02-06 18:59 UTC, gambinish commented on src/components/DemoTable.js
> +import { useEffect } from "react";
Added some documentation to `DemoTable` here: https://github.com/NMFS-RADFish/boilerplate/pull/26/commits/b69b34edf890c8f0f3e035e4692a939367cde090

2024-02-06 19:06 UTC, gambinish commented on src/App.js
> +          <Routes>
[ed71a5d](https://github.com/NMFS-RADFish/boilerplate/pull/26/commits/ed71a5de2c5513d9167a887e097129c9628478d4)

2024-02-07 17:52 UTC, brockinit approved these changes

2024-02-07 17:58 UTC, merged