205 restructure examples to follow template folder structure
NMFS-RADFish/boilerplate pull request #304
Opened 2024-10-14 01:24 UTC by jaygiang

issue #205 

The following changes were made to match the structure of `templates/react-javascript`
- Make sure that `App.jsx` has the following: 
  - `Application` container component
  - `GridContainer` trussworks component
  - `react-router-dom` components
- Create `pages/Home.jsx` if missing or change existing filename to `Home.jsx`
  - Move homepage code from `App.jsx` to `pages/Home.jsx`
- Remove unused files from `server-sync` example

2024-10-17 01:05 UTC, JCopeland-PIFSC requested changes
Please confirm that the individual examples where tested to run and build without error.

2024-10-17 17:46 UTC, jaygiang commented on examples/simple-table/src/pages/Home.jsx
> +    image: "https://picsum.photos/150/75",
@JCopeland-PIFSC Yeah I agree. Are there images you prefer to use? If not, I can look for something in unsplash.

2024-10-18 18:02 UTC, jaygiang commented on examples/simple-table/src/pages/Home.jsx
> +    image: "https://picsum.photos/150/75",
@JCopeland-PIFSC I used an unlicensed image from unsplash of a school of fish - lmk if this works. 
<img width="1134" alt="Screenshot 2024-10-18 at 10 59 13 AM" src="https://github.com/user-attachments/assets/c22c31d7-6ea9-43c1-ac5b-2bd85a8f945f">

2024-10-18 18:17 UTC, JCopeland-PIFSC commented on examples/simple-table/src/pages/Home.jsx
> +    image: "https://picsum.photos/150/75",
While I am not sure if this will work in the long run, I do think it is a big improvement over linking to picsum. At some point the governance team will need to determine if something like this has any licensing concerns. Looks good.

2024-10-18 19:28 UTC, jaygiang commented
> Please confirm that the individual examples where tested to run and build without error.

All examples are functioning without error. Please see notes below:

- Made a small update to `mock-api` example. When a user clicks the **Post Data** button, it returns an empty value. Changing the property name fixed it
- Found 2 issues not related to restructuring folder structure. Created issues for it below:
  - [Server Sync example - service worker error unsupported MIME type](https://github.com/orgs/NMFS-RADFish/projects/2/views/1?pane=issue&itemId=83985999)
  - [Simple Table - className error on spinner component](https://github.com/orgs/NMFS-RADFish/projects/2/views/1?pane=issue&itemId=83986169)

2024-10-22 19:27 UTC, JCopeland-PIFSC approved these changes
✅ LGTM

2024-10-22 21:29 UTC, merged