[RADFISH-54] Setup storage functionality for offline data
NMFS-RADFish/boilerplate pull request #32
Opened 2024-02-15 22:25 UTC by melsoriano

Create methods for storing offline data in `localStorage` or `indexedDB`.

Example usage:

```javascript
const indexedDBMethod = new IndexedDBMethod();
const indexedDBStorageModel = StorageModelFactory.createModel(indexedDBMethod);

indexedDBStorageModel.saveEntry(formData);
```

2024-02-15 23:20 UTC, brockinit commented on src/storage/LocalStorageMethod.js
> +export class LocalStorageMethod extends StorageMethod {
Can you add documentation to this file?

2024-02-15 23:20 UTC, brockinit commented on src/storage/IndexedDBMethod.js
> +export class IndexedDBMethod extends StorageMethod {
Can you add docs to this file?

2024-02-15 23:21 UTC, brockinit commented on src/storage/indexedDB.js
> +db.version(process.env.REACT_APP_INDEXED_DB_VERSION).stores({
Can you add documentation explaining how to add support for additional fields?

2024-02-15 23:22 UTC, brockinit commented on src/utilities/cryptoWrapper.js
> +export const generateUUID = () => {
Docs plz

2024-02-15 23:23 UTC, brockinit requested changes
Please add further documentation to make it clear to the end-developer how they can use/modify this functionality, if needed!

2024-02-19 21:43 UTC, thgaskell requested changes

2024-02-19 21:43 UTC, thgaskell commented on src/storage/LocalStorageMethod.js
> +export class LocalStorageMethod extends StorageMethod {
```suggestion
export class LocalStorageMethod extends StorageMethod {
  constructor (key) {
    this.key = key
  }
```

2024-02-19 21:43 UTC, thgaskell commented on src/storage/StorageMethod.js
> +  save(_data, _key) {
```suggestion
  create(_data) {
```

2024-02-19 21:43 UTC, thgaskell commented on src/storage/StorageMethod.js
> +  load(_key) {
```suggestion
  find(_criteria) {
```

2024-02-19 21:43 UTC, thgaskell commented on src/storage/StorageMethod.js
> +  editOne(_uuid, _data, _key) {
```suggestion
  update(_criteria, _data) {
```

2024-02-19 21:43 UTC, thgaskell commented on src/storage/StorageMethod.js
> +  loadOne(_uuid, _key) {
Let's remove this in favor of just `find`.

2024-02-20 21:37 UTC, melsoriano commented on src/storage/LocalStorageMethod.js
> +export class LocalStorageMethod extends StorageMethod {
Will add docs in a separate PR

2024-02-20 21:37 UTC, melsoriano commented on src/storage/IndexedDBMethod.js
> +export class IndexedDBMethod extends StorageMethod {
Will add docs in a separate PR

2024-02-20 21:37 UTC, melsoriano commented on src/utilities/cryptoWrapper.js
> +export const generateUUID = () => {
Will add docs in a separate PR

2024-02-20 21:37 UTC, melsoriano commented on src/storage/LocalStorageMethod.js
> +export class LocalStorageMethod extends StorageMethod {
Done ✅

2024-02-20 21:38 UTC, melsoriano commented on src/storage/StorageMethod.js
> +  load(_key) {
done ✅

2024-02-20 21:38 UTC, melsoriano commented on src/storage/StorageMethod.js
> +  loadOne(_uuid, _key) {
done ✅

2024-02-20 22:58 UTC, merged