Add screen shots to readme
NMFS-RADFish/boilerplate pull request #366
Opened 2024-10-15 23:40 UTC by IsaiahHarris

2024-10-16 18:21 UTC, jaygiang requested changes
Looks good, just a couple of things and suggestions:

- From what I remember, we don't want to include `package-lock.json`. @thgaskell can you verify?
- A suggestion, maybe we can add a title before the screenshot, like "Computed Form Fields App Preview" or leave a space before the screenshot? I think this will make it look a little more professional.
- [Multistep Form Example](https://github.com/NMFS-RADFish/boilerplate/tree/99-add-screen-shots/examples/multistep-form) screenshot image is broken
- [React Query](https://github.com/NMFS-RADFish/boilerplate/tree/99-add-screen-shots/examples/react-query) readme is titled **Mock API Example**

2024-10-21 22:52 UTC, jaygiang commented
@IsaiahHarris Can you remove all the `package-lock.json` when you can?

2024-10-21 22:55 UTC, jaygiang requested changes
@IsaiahHarris Can you remove all the `package-lock.json` when you can?

2024-10-23 19:08 UTC, thgaskell approved these changes

2024-10-28 16:44 UTC, jaygiang approved these changes

2024-10-28 19:36 UTC, merged