[RADFISH-105] Update favicons to RADFish logo
NMFS-RADFish/boilerplate pull request #52
Opened 2024-03-29 17:57 UTC by melsoriano

Update the vite config to use the RADFish icons

Homescreen icon screenshot on iPhone:

![radfish-icon-screenshot](https://github.com/NMFS-RADFish/boilerplate/assets/23709723/5e9a3b93-c2b9-4dbb-801b-059735decf16)

2024-03-29 19:17 UTC, gambinish approved these changes

2024-03-29 23:47 UTC, brockinit commented on index.html
> +    <title>RADFish PWA Boilerplate</title>
Can this be changed to just RADFish?

2024-03-29 23:48 UTC, brockinit commented on index.html
> +    <link rel="apple-touch-icon" href="/radfish.png" />
Do we need to add a similar icon for android?

2024-03-29 23:48 UTC, brockinit requested changes
Left a comment regarding the title, but otherwise looks good!

2024-04-02 19:05 UTC, melsoriano commented on index.html
> +    <link rel="apple-touch-icon" href="/radfish.png" />
The icons listed in the `vite.config.js` file is used for Android

2024-04-02 19:06 UTC, melsoriano commented on index.html
> +    <title>RADFish PWA Boilerplate</title>
Changed here: https://github.com/NMFS-RADFish/boilerplate/pull/52/commits/e0c1c2195339765604c804a13d3f8aa9d9948934

2024-04-03 15:23 UTC, merged