Create offline storage context wrapper
NMFS-RADFish/boilerplate pull request #76
Opened 2024-04-26 19:46 UTC by melsoriano

Created IndexedDB offline storage context wrapper

2024-05-02 22:03 UTC, brockinit commented on src/index.jsx
> +  name: import.meta.env.VITE_INDEXED_DB_NAME || "radfish_dev",
Recalling what Jesse had mentioned, I think we should avoid setting a default db name and instead let it error out if they don't supply one.

2024-05-02 22:04 UTC, brockinit commented on src/index.jsx
> +  name: import.meta.env.VITE_INDEXED_DB_NAME || "radfish_dev",
Along with provide a warning as to what's missing

2024-05-02 22:05 UTC, brockinit commented on src/packages/contexts/OfflineStorageWrapper.jsx
> +    throw new Error("useOfflineStorage must be used within an OfflineStorageWrapper");
It seems like during the build `context` is missing, causing it to hit line 45?

2024-05-02 22:10 UTC, brockinit commented on src/index.jsx
> +const offlineStorageConfig = {
Please provide a link to documentation here

2024-05-02 22:13 UTC, brockinit requested changes
Left some comments! I also didn't see data show up in the `formData` table when I submitted the ComplexForm 
<img width="1604" alt="image" src="https://github.com/NMFS-RADFish/boilerplate/assets/11274285/1073bf19-a3af-4843-8f4e-2456c3b8d60b">

2024-05-02 22:17 UTC, brockinit reviewed
Had one other question:

- What patterns can we follow to tie `useOfflineStorage` into the `FormWrapper` and `TableWrapper`? We want to ensure that things like onChange events are storing data into IndexDB as well as the React state. It doesn't look like `useOfflineStorage` is being used in the wrappers. It's just an unused import

2024-05-07 21:38 UTC, brockinit commented on src/contexts/FormWrapper.example.jsx
> +      // else {
Does this need to be commented out? @melsoriano

2024-05-08 12:50 UTC, brockinit approved these changes
We need to address the other comments left above, but I'm merging this for now so that we can ship release 0.8.0

2024-05-08 19:43 UTC, gambinish commented
Looks like tests are failing. I'm down to pair on this if you want.

2024-05-09 01:53 UTC, merged